CREATE TABLE colors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL UNIQUE,
    sort_order INT         NOT NULL
);

CREATE TABLE votes (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city     VARCHAR(100) NOT NULL,
    color_id BIGINT       NOT NULL REFERENCES colors (id),
    votes    INT          NOT NULL CHECK (votes >= 0),
    CONSTRAINT uq_votes_city_color UNIQUE (city, color_id)
);

CREATE INDEX idx_votes_color_id ON votes (color_id);
